version: 2.1 # Use v2.1 to enable orb usage.

# The Windows orb gives you everything you
# need to start using the Windows executor.
orbs:
  win: circleci/windows@2.2.0

jobs:
  build: # name of your job
    executor: win/default # executor type

    steps:
      # Commands are run in a Windows
      # virtual machine environment
      - checkout
      - run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - run: Remove-Item -Force -Recurse .git\
      - run: update-version.ps1
      - run: choco pack circleci-cli\circleci-cli.nuspec
      - run: copy-item circleci-cli.*.nupkg circleci-cli.nupkg
      - store_artifacts:
          path: circleci-cli.nupkg
      - run: choco push circleci-cli.nupkg --source https://chocolatey.org/ --apikey $env:apikey 
